magmafoundation/Magma

- build.gradle
> Fix Craftbukkit package being invalid mapped

- src/main/java/org/magmafoundation/magma/api/core/MagmaWorld.java
There is still quite a bit left for this, but most of the grunt work for this class should be complete. Many mixins still need to be set up and completed, but for the most part this class should be able to be referenced easily.
> Start work on MagmaWorld

- src/main/java/org/magmafoundation/magma/api/core/MagmaWorld.java
Adds a few more implementations for world methods. Was previously working on a version of Magma with some of this missing.
> Implement a few more world methods

- src/main/java/org/magmafoundation/magma/api/bridge/entity/IBridgeLivingEntity.java
- src/main/java/org/magmafoundation/magma/api/bridge/entity/player/IBridgePlayerEntity.java
- src/main/java/org/magmafoundation/magma/api/bridge/entity/player/IBridgeServerPlayerEntity.java
- src/main/java/org/magmafoundation/magma/api/core/MagmaServer.java
- src/main/java/org/magmafoundation/magma/api/core/MagmaWorld.java
- src/main/java/org/magmafoundation/magma/api/core/entity/MagmaPlayer.java
- src/main/java/org/magmafoundation/magma/api/mixin/entity/MixinEntity.java
- src/main/java/org/magmafoundation/magma/api/mixin/entity/MixinLivingEntity.java
- src/main/java/org/magmafoundation/magma/api/mixin/entity/player/MixinPlayerEntity.java
- src/main/java/org/magmafoundation/magma/api/mixin/entity/player/MixinServerPlayerEntity.java
This PR mainly adds some implementations for player as well as mixin(s) that correspond with it. There is also some work on server. I also apparently I had some stuff I did on world implementations a while back that I forgot to open a pull request for. Welp, here it is I guess 😄.
> Implement more server implementations and start work on player/human implementations

- patches/net/minecraftforge/fml/common/network/handshake/FMLHandshakeServerState.java.patch
- src/main/java/org/magmafoundation/magma/configuration/value/values/ArrayValue.java
- src/main/java/org/magmafoundation/magma/configuration/value/values/StringArrayValue.java
- src/main/java/org/magmafoundation/magma/configuration/value/values/StringValue.java
This fixes all the issues brought up in #97
- Fixes blacklistedmods.kickmessage being reset.
- Fixes formatting of blacklistedmods.list
- Fixes more then one mod being listed causing magma to not block any mods.
> Fixes issues with the blacklistmods config options.

- README.md
> Made the readme not look bad

- README.md
Also added note to run the jar via CMD
> Added note to not use installer version

- .github/ISSUE_TEMPLATE/feature_request.md
This would allow users to suggest things like other commands or things to add.
> Format for a feature request

- patches/net/minecraft/entity/player/EntityPlayerMP.java.patch
Fixes issue #220 by making all dimensions follow the overworld's keepInventory rule.
> Fixes #220 keepInventory  issue

- README.md
> Added info on the new subreddit

- src/main/java/org/bukkit/command/defaults/ReloadCommand.java
Adds a /reload confirm command to confirm a reload if mods are installed
> Add reload confirmation if mods are installed

- README.md
Add information about BungeeCord in README
> Add information about BungeeCord

- patches/net/minecraft/server/management/PlayerList.java.patch
Use whitelist message from spigot.yml
> Fix customizable whitelist message

- patches/net/minecraft/command/FunctionObject.java.patch
Fixes BukkitSender NullPointer (See #231)
> Fix NullPointer in FunctionObject (Fixes #231)

- patches/net/minecraftforge/event/world/BlockEvent.java.patch
- src/main/java/org/bukkit/craftbukkit/v1_12_R1/event/CraftEventFactory.java
- src/main/java/org/magmafoundation/magma/configuration/MagmaConfig.java
- src/main/java/org/magmafoundation/magma/modPatcher/patches/NaturesCompassPatch.java
Hex i need you to work out how to make the nature's compass patch work because I don't really understand how the mod patching works. I tried my best but idk what to do. Also fixed issue #360
> Attempted nature's compass patch and fixed blockBreakEvent drops

- README.md
- patches/net/minecraft/server/MinecraftServer.java.patch
- src/main/java/org/magmafoundation/magma/commands/MagmaCommand.java
- src/main/java/org/magmafoundation/magma/commands/VersionCommand.java
- src/main/java/org/magmafoundation/magma/configuration/MagmaConfig.java
- Update Forge version 
- Implemented permission check instead of OP check in version command
- Updated dumps (added biome dump)
> Dump update and /version permission

- README.md
- patches/net/minecraftforge/fml/common/FMLCommonHandler.java.patch
- patches/net/minecraftforge/fml/common/network/internal/FMLNetworkHandler.java.patch
- src/main/java/org/bukkit/potion/PotionEffectType.java
- src/main/java/org/magmafoundation/magma/configuration/MagmaConfig.java
- Fixed PotionEffectType ArrayIndexOutOfBoundsException by adding a config entry
- Fixed FML messages
- Added customizable "Server ist still starting" message
- Updated BungeeCord recommendation in README
> Fixed PotionEffectType and FML messages

- src/main/java/org/bukkit/plugin/java/PluginClassLoader.java
- src/main/java/org/magmafoundation/magma/api/ServerAPI.java
- src/main/java/org/magmafoundation/magma/configuration/MagmaConfig.java
Added an api for oredict entries in the ServerAPI
> Bukkit OreDict API + Forge-Bukkit-Access

- src/main/java/org/bukkit/Material.java
- src/main/java/org/bukkit/craftbukkit/v1_12_R1/inventory/CraftItemFactory.java
- src/main/java/org/bukkit/craftbukkit/v1_12_R1/inventory/CraftItemStack.java
- src/main/java/org/bukkit/craftbukkit/v1_12_R1/inventory/CraftMetaBlockState.java
Possible fix for #390, #350 and #389
> Fix NBT erasing error (Fixes #453)

- README.md
- patches/net/minecraftforge/common/ForgeVersion.java.patch
- patches/net/minecraftforge/server/terminalconsole/MinecraftFormattingConverter.java.patch
> Update Forge to 2860

- src/main/java/org/magmafoundation/magma/commands/MagmaCommand.java
The new format fits the /plugin command more
> Fix mod command format
